export const FETCH_DATA = "FETCH_DATA";
export const FETCH_SINGLE_DATA = "FETCH_SINGLE_DATA";
export const TODO_LIST_DATA = "TODO_LIST_DATA";
export const TODO_SINGLE_LIST_DATA = "TODO_SINGLE_LIST_DATA";
export const SINGLE_USER_LOGIN = "SINGLE_USER_LOGIN";
export const ACCOUNT_LIST_USERS = "ACCOUNT_LIST_USERS";
export const DELETE_USER_FROM_LIST = "DELETE_USER_FROM_LIST";
export const ADD_NEW_PRODUCT_IN_LIST = "ADD_NEW_PRODUCT_IN_LIST";
